### ISSUE TITLE
Spectrify only supports schema "public"

### ISSUE THREAD

**Issue by c-nichols** [hellonarrativ/spectrify#11]
```
$ spectrify --host=redshift.mysite.com --user=myuser --db=mydb convert my_schema.my_table 's3://my-bucket/spectrum/my_table/'
Traceback (most recent call last):
  File "/home/colin/bin/spectrify", line 11, in <module>
...
  File "/opt/python3.6/site-packages/sqlalchemy_redshift/dialect.py", line 636, in _get_redshift_relation
    raise sa.exc.NoSuchTableError(key)
sqlalchemy.exc.NoSuchTableError: public.my_schema.my_table
```

**Comment by naveenarumugam** [comment]
Thanks @c-nichols  

For now, I am passing the MetaData object to each method (with propogated changes)  and able to do parquet generation step.
