### ISSUE TITLE
ValueError: Type <class 'sqlalchemy.sql.sqltypes.DATE'> not currently supported by Spectrify

### ISSUE THREAD

**Issue by naveenarumugam** [hellonarrativ/spectrify#15]
* Spectrify version: 0.4.0
* Python version: 2.7 
* Operating System: Mac

### Description

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/spectrify/utils/schema.py", line 54, in get_table_schema2
    col.type.__class__
ValueError: Type <class 'sqlalchemy.sql.sqltypes.DATE'> not currently supported by Spectrify. Open an issue?

### What I Did

```
sa_table = get_table_schema(sa_engine, 'my_table', meta)
```

**Comment by naveenarumugam** [comment]
@c-nichols  I am able to workaround this problem.  But, would be nice to have it integrated with spectrify. 
Right now, I am using PyArrow String in place of sqlalchemy DATE. Will see if any other problem arises.

**Comment by naveenarumugam** [comment]
Btw,  should I use **date32** ? so far, no problems noticed .. except in the parquet schema it's showing as **binary** instead of string  ...but, the value is read properly in the external table.

**Comment by andrewgross** [comment]
Redshift Spectrum recently added support for Parquet DATE, so it would be a good time to get this in.  It should be a `date32` in my experience, but it will need some preprocessing before ingestion.  If you have a string date `"2018-01-01"` this cannot be loaded by PyArrow.  Instead you need to convert it to the integer number of days since epoch.

See the (very sparse) docs [here](https://arrow.apache.org/docs/python/generated/pyarrow.date32.html)

I did some testing with `DATE` fields and here is some sample code I used to convert a string to the format required for a `date32` PyArrow field.  Not sure if `date64` would require anything different.  Also not sure if Pandas has better vectorized support via `to_datetime` or other functions that would make it easier to convert an array of string dates to integers suitable for consumption.

```python
import datetime
import pyarrow as pa
import pyarrow.parquet as pq
import pandas as pd


_date = datetime.datetime.strptime("2018-01-01", "%Y-%m-%d")
days_since_epoch = (_date - datetime.datetime(1970, 1, 1)).days

column_data = {"foo": [days_since_epoch], "id": [1]}

fields = []
fields.append(pa.field("foo", pa.date32()))
fields.append(pa.field("id", pa.int32()))
schema = pa.schema(fields)

array_data = []
array_data.append(pa.array(column_data["foo"], type=pa.date32()))
array_data.append(pa.array(column_data["id"], type=pa.int32()))

record_batch = pa.RecordBatch.from_arrays(array_data, schema.names)

table = pa.Table.from_batches([record_batch])
pq.write_table(table, "/Users/foo/parquet/test.parq")
```

**Comment by naveenarumugam** [comment]
@andrewgross  just tried it.  So, the date is being written as 17532 (in the file); not sure, how it will be represented in the parquet table. Meanwhile, in my current version, the string representation of the date was shown as  binary in the schema; but, taken properly in the table
`foo = 17532
id = 1`

**Comment by c-nichols** [comment]
@andrewgross @naveenarumugam thanks so much for the input and code.  I'm going to integrate this over the next week, along with some general refactoring to make working with the code easier.  Hoping to share the project with a larger audience before too long, so am setting aside some time to work on it!
