### ISSUE TITLE
When unloading dates before the year "1000" CSV parsing errors.

### ISSUE THREAD

**Issue by troxil** [hellonarrativ/spectrify#53]
* Spectrify version: 2.0
* Python version: 3.6
* Operating System: OSX

### Description
Unloading a `DATE` column that has dates before the year `1000` causes failures.

```sql
CREATE TABLE IF NOT EXISTS public.my_dodgy_test (
  fun_date DATE
);
INSERT INTO public.my_dodgy_test VALUES ('0030-01-01');
SELECT fun_date from public.my_dodgy_test;
```

I know this issue is due to the `UNLOAD` doesn't pad the leading 0's in when writing the CSV correctly. but I'm unsure how to deal with this?

Source of the problem is in here https://github.com/hellonarrativ/spectrify/blob/master/spectrify/utils/timestamps.py#L35

### What I Did
```
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/myself/dev/spectrify/.venv/lib/python3.7/site-packages/spectrify/convert.py", line 215, in _parallel_wrapper
    CsvConverter(sa_table, s3_config, delimiter, escapechar, quoting, unicode_csv).convert_csv(data_path)
  File "/Users/myself/dev/spectrify/.venv/lib/python3.7/site-packages/spectrify/convert.py", line 120, in convert_csv
    for chunk in self.columnar_data_chunks(file_path, self.sa_table, SPECTRIFY_ROWS_PER_GROUP):
  File "/Users/myself/dev/spectrify/.venv/lib/python3.7/site-packages/spectrify/convert.py", line 168, in columnar_data_chunks
    value = self._convert_to_type(value, py_type)
  File "/Users/myself/dev/spectrify/.venv/lib/python3.7/site-packages/spectrify/convert.py", line 143, in _convert_to_type
    value = py_type(value)
  File "/Users/myself/dev/spectrify/.venv/lib/python3.7/site-packages/spectrify/utils/timestamps.py", line 36, in iso8601_to_days_since_epoch
    dt = ciso8601.parse_datetime(date_str)
ValueError: Invalid character while parsing year ('-', Index: 2)
"""
```

**Comment by c-nichols** [comment]
oof, this is a tough one.  Does ISO-8601 specify what to do for non-4-digit years?

**Comment by c-nichols** [comment]
(Inadvertent button push lol)

**Comment by ms32035** [comment]
I experienced the same issue with negative years (unloaded as `-1`), so please bear that edge case in mind too when thinking about solutions

**Comment by hawktang** [comment]
If you want  to del it, just follow customize section of the document to rewire query to filter out the records.

**Comment by hawktang** [comment]
I encounter it long time ago with even BC years
